version: '3'
services:
 nagios:
  image: myimage/nagios
  container_name: nagios
  networks:
      mynet:
  ports:
   - 8080:80
  environment:
   - NAGIOSADMIN_USER=nagiosadmin
   - NAGIOSAMDIN_PASS=nagios
   - NAGIOS_TIMEZONE=Asia/Kolkata
  volumes:
   - /srv/nagios/etc:/opt/nagios/etc
   - /srv/nagios/var:/opt/nagios/var
   - /srv/nagios/custom_plugins:/opt/Custom-Nagios-Plugins
   - /srv/nagios/nagios_graph_var:/opt/nagiosgraph/var
   - /srv/nagios/nagios_graph_etc:/opt/nagiosgraph/etc
networks:
  mynet:
